/**
 * Typed Supabase client helpers.
 *
 * Because this codebase's Database type in src/types/database.ts is a
 * hand-maintained definition (not auto-generated by supabase gen types),
 * the Supabase JS client's internal mutation overloads sometimes resolve
 * table Insert/Update generics to `never` when the generic parameter chain
 * differs from the expected format.
 *
 * We expose a thin `db` helper that casts the client to `unknown` first and
 * then to the correct typed client, bypassing the overload resolution issue
 * while preserving full type safety at the call-site via explicit generics.
 */

import { supabase } from './supabase';
import type { Database } from '../types/database';
import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * Returns the typed Supabase client.
 * Use this in service files for INSERT/UPDATE/DELETE where the `as any`
 * workaround was previously needed.
 */
export function db(): SupabaseClient<Database> {
  return supabase as unknown as SupabaseClient<Database>;
}
